add prefix config from environment variable
bitnami/bitnami-docker-phppgadmin pull request #4
Opened 2021-08-10 20:34 UTC by C-Romeo

In case when app needs to be prefixed for a proxy server for eg then by setting environment variable `PHPPGADMIN_URL_PREFIX` to `/phppgadmin` will allow access of app by an url prefix `http://localhost/phppgadmin`.

As a result the following file `/opt/bitnami/apache/conf/bitnami/phppgadmin.conf`  will be included in httpd.config of the apache server.

```
Alias /phppgadmin "/opt/bitnami/phppgadmin"
<Directory "/opt/bitnami/phppgadmin">
  Options -Indexes +FollowSymLinks -MultiViews
  AllowOverride All
  Require all granted
</Directory>
```

2021-08-11 10:07 UTC, alemorcuq requested changes
Thanks for the PR! Please, check my comments.

Also, please add the `PHPPGADMIN_URL_PREFIX` variable to the `phppgadmin-env.sh` file.

2021-08-11 10:07 UTC, alemorcuq commented on 7/debian-10/rootfs/opt/bitnami/scripts/phppgadmin/setup.sh
> +then
```suggestion
if is_empty_value "$PHPPGADMIN_URL_PREFIX"; then
```

2021-08-11 10:07 UTC, alemorcuq commented on 7/debian-10/rootfs/opt/bitnami/scripts/phppgadmin/setup.sh
> +then
Let's also load the `libvalidations.sh` library to have access to the `is_empty_value` function.

2021-08-11 10:07 UTC, alemorcuq commented on README.md
> +- `PHPPGADMIN_URL_PREFIX`: URL prefix from where it will be accessible (i.e. /phppgadmin)
```suggestion
- `PHPPGADMIN_URL_PREFIX`: URL prefix from where it will be accessible (e.g. /phppgadmin). No default.
```

2021-08-11 10:07 UTC, alemorcuq commented on 7/debian-10/rootfs/opt/bitnami/scripts/phppgadmin/setup.sh
> +fi
Add a newline at the end.

2021-08-11 14:18 UTC, C-Romeo commented on 7/debian-10/rootfs/opt/bitnami/scripts/phppgadmin/setup.sh
> +fi
exists

2021-08-11 14:19 UTC, C-Romeo commented on 7/debian-10/rootfs/opt/bitnami/scripts/phppgadmin/setup.sh
> +fi
exist

2021-08-12 12:54 UTC, C-Romeo commented
Review suggestions were completed. Thanks

2021-08-12 14:44 UTC, alemorcuq approved these changes
Thanks for the PR! Changes LGTM, but I have to integrate them into the system before merging your PR.

2021-08-19 08:51 UTC, rafariossaa commented
Hi,
  Sorry for the delay, @alemorcuq will be back in a couple of days.

2021-09-07 01:55 UTC, C-Romeo commented
Hi @alemorcuq, any updates on merge?

2021-09-07 07:07 UTC, alemorcuq commented
Sorry, @C-Romeo, we lost track of this ticket. I'm on it right now, you can expect it to be ready today.

2021-09-07 08:57 UTC, merged

2021-09-07 08:58 UTC, alemorcuq commented
A new container should be released in the next hours, @C-Romeo. Thanks for the contribution and sorry for the delay.

2021-09-07 18:24 UTC, C-Romeo commented
I've switched to the official image and now it works with prefix environment setting. Many thanks